accounts/urls.py
from django.urls import path

from . import views


app_name = "accounts"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("login", views.LoginView.as_view(), name="login"),
    path("register", views.RegisterView.as_view(), name="register"),
    path("logout", views.LogoutView.as_view(), name="logout"),
    path("forgot-pass", views.ForgotPasswordView.as_view(), name="forgot-pass"),
    path("resend-verification", views.ResendVerificationView.as_view(), name="resend-verification"),
    path("verify/<str:token>", views.AccountVerificationView.as_view(), name="verify"),
    path("reset-pass/<str:token>", views.ResetPasswordView.as_view(), name="reset-pass"),
    path("profile", views.ProfileView.as_view(), name="profile"),
    path("change-profile-pic", views.ChangeProfilePicView.as_view(), name="change-profile-pic"),
    path("unsubscribe/", views.UnsubscribeView.as_view(), name="unsubscribe")
]

capstone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path

from . import views


app_name = "news"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("headlines/<str:category>", views.HeadlinesView.as_view(), name="headlines"),
    path("sources/", views.SourcesView.as_view(), name="sources"),
    path("search", views.SearchView.as_view(), name="search"),
    path("subscribe/", views.SubscribeView.as_view(), name="subscribe"),
    path("discover/", views.DiscoverView.as_view(), name="discover"),
    path("faqs/", views.FAQsView.as_view(), name="faqs"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("privacy-policy/", views.PrivacyPolicyView.as_view(), name="privacy-policy")
]

news/models.py
from django.db import models

from accounts.models import User


# Create your models here.
class Subscription(models.Model):
    source_id = models.CharField(max_length=64)
    source_name = models.CharField(max_length=64)
    source_category = models.CharField(max_length=64)
    source_description = models.CharField(max_length=1200)
    source_url = models.URLField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="subscriptions")
    
    def serializer(self):
        return {
            "id": self.source_id,
            "name": self.source_name,
            "category": self.source_category,
            "description": self.source_description,
            "url": self.source_url
        }

news/views.py
import json

from django.shortcuts import render
from django.views import View
from django.http import JsonResponse

from .models import Subscription
from .utils import get_top_headlines, get_top_sources, get_all_sources, get_everything, get_news_from_sources


# Create your views here.
class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "news/index.html")
    
    
class HeadlinesView(View):
    def get(self, request, category):
        
        # Get top headlines
        response = get_top_headlines(category)
                        
        # Get top sources and add to response
        sources = get_top_sources(category)
        
        if response["status"] == "ok" and sources["status"] == "ok":
            response["sources"] = sources["sources"]
                
        # Get user's subscriptions if user is authenticated
        if request.user.is_authenticated and response["status"] == "ok":
            
            # Get all subscriptions of current user
            subscribed_sources = request.user.subscriptions.all()
            
            # Append source to subscribed list in response if both source's ids match
            for source in response["sources"]:
                for sub in subscribed_sources:
                    if source["id"] == sub.source_id:
                        source["subscribed"] = True
                        break
                
        return JsonResponse(response, safe=False, status=200)
    
    
class SourcesView(View):
    def get(self, request, *args, **kwargs):
        
        response = get_all_sources()
                
        # Get user's subscriptions if user is authenticated
        if request.user.is_authenticated and response["status"] == "ok":
            
            # Get all subscriptions of current user
            subscribed_sources = request.user.subscriptions.all()
            
            # Append source to subscribed list in response if both source's ids match
            for sub in subscribed_sources:
                for source in response["sources"]:
                    if source["id"] == sub.source_id:
                        source["subscribed"] = True
                        break
        
        return JsonResponse(response, safe=False, status=200)
    
    
class SearchView(View):
    def get(self, request, *args, **kwargs):
        
        # If query string given as get param
        if request.GET.get("q"):
            q = request.GET["q"]
            response = get_everything(q=q)
            
            return JsonResponse(response, safe=False, status=200)
        
        # Else render search template
        return render(request, "news/search.html")
    
    
class SubscribeView(View):
    def post(self, request, *args, **kwargs):
        
        # Check if user is authenticated
        if not request.user.is_authenticated:
            return JsonResponse({"error": "Not logged in."}, status=403)
        
        # Load json data
        data = json.loads(request.body)
        if not data.get("source"):
            return JsonResponse({"error": "Invalid data."}, status=400)
        
        source = json.loads(data["source"])
        print(source["id"])
        
        # Toggle subscription for current user
        try:
            sub = Subscription.objects.get(source_id=source["id"], user=request.user)
            sub.delete()
            
            return JsonResponse({"messsage": "Subscription removed.", "subscribed": False}, status=201)
        except Subscription.DoesNotExist:
            sub = Subscription.objects.create(
                source_id=source["id"], 
                source_name=source["name"], 
                source_category=source["category"], 
                source_description=source["description"],
                source_url=source["url"],
                user=request.user
                )
            sub.save()
            
            return JsonResponse({"messsage": "Subscription created.", "subscribed": True}, status=201)     
        
       
class DiscoverView(View):    
    def get(self, request, *args, **kwargs):
        
        # Check if logged in
        if not request.user.is_authenticated:
            return JsonResponse({"messsage": "Not logged in."}, status=403)
        
        # Get subscriptions list
        subscriptions = request.user.subscriptions.all()
        
        # Get all news from current user's subscriptions list
        sources = [source.serializer() for source in subscriptions]
        response = get_news_from_sources([source["id"] for source in sources])
        
        # Append subscribed source to response
        if response["status"] == "ok":
            response["sources"] = sources
            # Set subscribed to True for each source
            for source in response["sources"]:
                source["subscribed"] = True
        
        return JsonResponse(response, safe=False, status=200)
    
    
class FAQsView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "news/faqs.html")
    

class AboutView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "news/about.html")
    

class PrivacyPolicyView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "news/privacy-policy.html")
        

news/templates/news/about.html
{% extends "news/layout.html" %}

{% block title %} About Us {% endblock %}

{% block body %}

    <div class="px-4 pt-5 my-5 text-center">
        <h1 class="display-5 fw-bold text-body-emphasis blog-header-logo">Who am I?</h1>
        <div class="col-lg-6 mx-auto">
            <p class="lead mb-4">A software engineering graduate focused on providing best technical solutions to the world.</p>
            <div class="my-5">
                <ul class="list-unstyled d-flex justify-content-center h-100 gap-5">
                    <li>
                        <a class="link-underline link-underline-opacity-0 d-flex flex-column" href="https://youtube.com/@srkydev5727?si=DXxxpW-AAnEOUCOr">
                            <i class="fa fa-3x fa-facebook"></i>Facebook
                        </a>
                    </li>
                    <li class="ms-3">
                        <a class="link-underline link-underline-opacity-0 d-flex flex-column" href="https://youtube.com/@srkydev5727?si=DXxxpW-AAnEOUCOr">
                            <i class="fa fa-3x fa-youtube-play"></i>Youtube
                        </a>
                    </li>
                    <li class="ms-3">
                        <a class="link-underline link-underline-opacity-0 d-flex flex-column" href="https://www.linkedin.com/in/shahrukh-khan-2b8968242/">
                            <i class="fa fa-3x fa-linkedin"></i>LinkedIn
                        </a>
                    </li>
                    <li class="ms-3">
                        <a class="link-underline link-underline-opacity-0 d-flex flex-column" href="https://github.com/srky420/">
                            <i class="fa fa-3x fa-github"></i>Github
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

{% endblock %}

news/templates/news/discover.html
<!-- Subscriptions -->
<div id="subscriptions" class="my-5">
    
</div>

<!-- News from subscriptions -->
<div id="subscriptions-news" class="my-5">

</div>

news/templates/news/footer.html
<div class="mt-auto bg-body-tertiary border-top">
    <div class="container">
        <footer class="footer pt-5">
            <div class="row justify-content-lg-between">
    
                <div class="col-3 mb-3">
                    <ul class="nav flex-column">
                        <li class="nav-item mb-2"><a href="{% url 'news:index' %}" class="nav-link p-0 text-body-secondary">Home</a></li>
                        <li class="nav-item mb-2"><a href="{% url 'news:search' %}" class="nav-link p-0 text-body-secondary">Search</a></li>
                        <li class="nav-item mb-2"><a href="{% url 'accounts:index' %}" class="nav-link p-0 text-body-secondary">Account</a></li>
                    </ul>
                </div>

                <div class="col-4 mb-3">
                    <ul class="nav flex-column">
                        <li class="nav-item mb-2"><a href="{% url 'news:faqs' %}" class="nav-link p-0 text-body-secondary">FAQs</a></li>
                        <li class="nav-item mb-2"><a href="{% url 'news:privacy-policy' %}" class="nav-link p-0 text-body-secondary">Privacy Policy</a></li>
                        <li class="nav-item mb-2"><a href="{% url 'news:about' %}" class="nav-link p-0 text-body-secondary">About Us</a></li>
                    </ul>
                </div>

                <div class="col-5 mb-3">
                    <ul class="list-unstyled d-flex justify-content-end align-items-center h-100">
                        <li class="ms-3"><a class="link-body-emphasis" href="https://www.facebook.com/profile.php?id=100082964377668&mibextid=ZbWKwL"><i class="fa fa-2x fa-facebook"></i></a></li>
                        <li class="ms-3"><a class="link-body-emphasis" href="https://youtube.com/@srkydev5727?si=DXxxpW-AAnEOUCOr"><i class="fa fa-2x fa-youtube-play"></i></a></li>
                        <li class="ms-3"><a class="link-body-emphasis" href="https://www.linkedin.com/in/shahrukh-khan-2b8968242/"><i class="fa fa-2x fa-linkedin"></i></a></li>
                        <li class="ms-3"><a class="link-body-emphasis" href="https://github.com/srky420/"><i class="fa fa-2x fa-github"></i></a></li>
                    </ul>
                </div>
            </div>

            <div class="py-4 border-top">
                <p>News © 2023 Company, Inc. All rights reserved.</p>
            </div>
        </footer>
    </div>
</div>

news/templates/news/index.html
{% extends "news/layout.html" %}

{% block title %} Index {% endblock %}

{% block body %}

    {% include "news/tab-content.html" %} 

{% endblock %}

news/templates/news/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <link rel="shortcut icon" href="{% static 'news/favicon/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'news/styles.css' %}">
    <title>News: {% block title %}{% endblock %}</title>
</head>
<body class="d-flex flex-column min-vh-100 position-relative">

    {% if request.resolver_match.url_name == "index" %}

        <!-- Navbar -->
        {% include "news/navbar-primary.html" %}

    {% else %}

        {% include "news/navbar-secondary.html" %}
       
    {% endif %}

    <!-- Body block -->
    <div class="container">
        {% block body %}{% endblock %}
    </div>
    
    <!-- Footer -->
    {% include "news/footer.html" %}

    <!-- Color modes -->
    {% include "news/color-modes.html" %}


    <!-- Scripts -->
    {% if request.resolver_match.url_name == "index" %}
        <script src="{% static 'news/sources.js' %}"></script>
        <script src="{% static 'news/carousel.js' %}"></script>
        <script src="{% static 'news/tabs.js' %}"></script>
        <script src="{% static 'news/main.js' %}"></script>
        <script src="{% static 'news/subscribe.js' %}"></script>
    {% endif %}
    
    {% block scripts %}{% endblock %}

    <script src="{% static 'news/articles.js' %}"></script>
    <script src="{% static 'news/placeholders.js' %}"></script>
    <script src="{% static 'news/reload.js' %}"></script>
    <script src="{% static 'news/color-modes.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>

</body>
</html>

news/templates/news/navbar-primary.html
<div class="container container-lg">
    <header class="border-bottom lh-1 py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-4 pt-1">
                <a class="link-body-emphasis" href="{% url 'news:search' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                    </svg>
                </a>
            </div>
            <div class="col-4 text-center">
                <a class="blog-header-logo text-body-emphasis text-decoration-none" href="{% url 'news:index' %}">News</a>
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
                {% if request.user.is_authenticated %}
                        <div class="dropdown">
                            <button class="btn bg-transparent border-0 p-0" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <img src="{{ request.user.profile_pic.url }}" class="profile-pic profile-pic-md" alt="profile-pic">
                            </button>
                            <ul class="dropdown-menu dropdown-menu-end">
                                <li class="text-center border-bottom p-2 pb-3 mb-2"><strong>{{ request.user.username }}</strong></li>
                                <li><a class="dropdown-item p-2" href="{% url 'accounts:profile' %}">Profile</a></li>
                                <li><a class="dropdown-item p-2" href="{% url 'accounts:logout' %}">Log out</a></li>
                            </ul>
                        </div>
                    </a>
                {% else %}
                    <a class="btn btn-sm btn-dark" href="{% url 'accounts:index' %}">Sign up</a>
                {% endif %}
            </div>
        </div>
    </header>

    <div class="nav-scroller py-1">
        <nav class="nav nav-underline justify-content-between">
            <button class="tab-btn nav-item nav-link link-body-emphasis active" id="world-tab" data-tab-name="world" data-bs-toggle="tab" data-bs-target="#world-tab-pane" type="button" role="tab" aria-controls="world-tab-pane" aria-selected="true">World</button>
            <button class="tab-btn nav-item nav-link link-body-emphasis" id="business-tab" data-tab-name="business" data-bs-toggle="tab" data-bs-target="#business-tab-pane" type="button" role="tab" aria-controls="business-tab-pane" aria-selected="false">Business</button>
            <button class="tab-btn nav-item nav-link link-body-emphasis" id="entertainment-tab" data-tab-name="entertainment" data-bs-toggle="tab" data-bs-target="#entertainment-tab-pane" type="button" role="tab" aria-controls="entertainment-tab-pane" aria-selected="false">Entertainment</button>
            <button class="tab-btn nav-item nav-link link-body-emphasis" id="general-tab" data-tab-name="general" data-bs-toggle="tab" data-bs-target="#general-tab-pane" type="button" role="tab" aria-controls="general-tab-pane" aria-selected="false">General</button>
            <button class="tab-btn nav-item nav-link link-body-emphasis" id="health-tab" data-tab-name="health" data-bs-toggle="tab" data-bs-target="#health-tab-pane" type="button" role="tab" aria-controls="health-tab-pane" aria-selected="false">Health</button>
            <button class="tab-btn nav-item nav-link link-body-emphasis" id="science-tab" data-tab-name="science" data-bs-toggle="tab" data-bs-target="#science-tab-pane" type="button" role="tab" aria-controls="science-tab-pane" aria-selected="false">Science</button>
            <button class="tab-btn nav-item nav-link link-body-emphasis" id="sports-tab" data-tab-name="sports" data-bs-toggle="tab" data-bs-target="#sports-tab-pane" type="button" role="tab" aria-controls="sports-tab-pane" aria-selected="false">Sports</button>
            <button class="tab-btn nav-item nav-link link-body-emphasis" id="technology-tab" data-tab-name="technology" data-bs-toggle="tab" data-bs-target="#technology-tab-pane" type="button" role="tab" aria-controls="technology-tab-pane" aria-selected="false">Technology</button>
            <button class="tab-btn nav-item nav-link link-body-emphasis" id="discover-tab" data-tab-name="discover" data-bs-toggle="tab" data-bs-target="#discover-tab-pane" type="button" role="tab" aria-controls="discover-tab-pane" aria-selected="false">Discover</button>
            <button class="tab-btn nav-item nav-link link-body-emphasis" id="sources-tab" data-tab-name="sources" data-bs-toggle="tab" data-bs-target="#sources-tab-pane" type="button" role="tab" aria-controls="sources-tab-pane" aria-selected="false">Sources</button>
        </nav>
    </div>
</div>
<hr class="m-0">

news/templates/news/navbar-secondary.html
<!-- Header -->
<header class="lh-1 py-3 border-bottom">
    <div class="container">
        <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-4 pt-1">
                <a class="link-body-emphasis" href="{% url 'news:index' %}" aria-label="Search">
                    <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-arrow-left-square" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M15 2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2zM0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm11.5 5.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                    </svg>
                </a>
            </div>
            <div class="col-4 text-center">
                <a class="blog-header-logo text-body-emphasis text-decoration-none" href="{% url 'news:index' %}">News</a>
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
                {% if request.user.is_authenticated %}
                        <div class="dropdown">
                            <button class="btn bg-transparent border-0 p-0" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <img src="{{ request.user.profile_pic.url }}" class="profile-pic profile-pic-md" alt="profile-pic">
                            </button>
                            <ul class="dropdown-menu dropdown-menu-end">
                                <li class="text-center border-bottom p-2 pb-3 mb-2"><strong>{{ request.user.username }}</strong></li>
                                <li><a class="dropdown-item p-2" href="{% url 'accounts:profile' %}">Profile</a></li>
                                <li><a class="dropdown-item p-2" href="{% url 'accounts:logout' %}">Log out</a></li>
                            </ul>
                        </div>
                    </a>
                {% else %}
                    <a class="btn btn-sm btn-dark" href="{% url 'accounts:index' %}">Sign up</a>
                {% endif %}
            </div>
        </div>
    </div>
</header>

news/templates/news/navbar.html
<div class="container-lg">
    <header class="border-bottom lh-1 py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-4 pt-1">
                <a class="link-body-emphasis" href="{% url 'news:search' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                    </svg>
                </a>
            </div>
            <div class="col-4 text-center">
                <a class="blog-header-logo text-body-emphasis text-decoration-none" href="{% url 'news:index' %}">News</a>
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
                {% if request.user.is_authenticated %}
                        <div class="dropdown">
                            <button class="btn bg-transparent border-0 p-0" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <img src="{{ request.user.profile_pic.url }}" class="profile-pic profile-pic-md" alt="profile-pic">
                            </button>
                            <ul class="dropdown-menu dropdown-menu-end">
                                <li class="text-center border-bottom p-2 pb-3 mb-2"><strong>{{ request.user.username }}</strong></li>
                                <li><a class="dropdown-item p-2" href="{% url 'accounts:profile' %}">Profile</a></li>
                                <li><a class="dropdown-item p-2" href="{% url 'accounts:logout' %}">Log out</a></li>
                            </ul>
                        </div>
                    </a>
                {% else %}
                    <a class="btn btn-sm btn-dark" href="{% url 'accounts:index' %}">Sign up</a>
                {% endif %}
            </div>
        </div>
    </header>

    <div class="nav-scroller py-1">
        <nav class="nav nav-underline justify-content-between">
            <button class="tab-btn nav-item nav-link link-body-emphasis active" id="world-tab" data-tab-name="world" data-bs-toggle="tab" data-bs-target="#world-tab-pane" type="button" role="tab" aria-controls="world-tab-pane" aria-selected="true">World</button>
            <button class="tab-btn nav-item nav-link link-body-emphasis" id="business-tab" data-tab-name="business" data-bs-toggle="tab" data-bs-target="#business-tab-pane" type="button" role="tab" aria-controls="business-tab-pane" aria-selected="false">Business</button>
            <button class="tab-btn nav-item nav-link link-body-emphasis" id="entertainment-tab" data-tab-name="entertainment" data-bs-toggle="tab" data-bs-target="#entertainment-tab-pane" type="button" role="tab" aria-controls="entertainment-tab-pane" aria-selected="false">Entertainment</button>
            <button class="tab-btn nav-item nav-link link-body-emphasis" id="general-tab" data-tab-name="general" data-bs-toggle="tab" data-bs-target="#general-tab-pane" type="button" role="tab" aria-controls="general-tab-pane" aria-selected="false">General</button>
            <button class="tab-btn nav-item nav-link link-body-emphasis" id="health-tab" data-tab-name="health" data-bs-toggle="tab" data-bs-target="#health-tab-pane" type="button" role="tab" aria-controls="health-tab-pane" aria-selected="false">Health</button>
            <button class="tab-btn nav-item nav-link link-body-emphasis" id="science-tab" data-tab-name="science" data-bs-toggle="tab" data-bs-target="#science-tab-pane" type="button" role="tab" aria-controls="science-tab-pane" aria-selected="false">Science</button>
            <button class="tab-btn nav-item nav-link link-body-emphasis" id="sports-tab" data-tab-name="sports" data-bs-toggle="tab" data-bs-target="#sports-tab-pane" type="button" role="tab" aria-controls="sports-tab-pane" aria-selected="false">Sports</button>
            <button class="tab-btn nav-item nav-link link-body-emphasis" id="technology-tab" data-tab-name="technology" data-bs-toggle="tab" data-bs-target="#technology-tab-pane" type="button" role="tab" aria-controls="technology-tab-pane" aria-selected="false">Technology</button>
            <button class="tab-btn nav-item nav-link link-body-emphasis" id="discover-tab" data-tab-name="discover" data-bs-toggle="tab" data-bs-target="#discover-tab-pane" type="button" role="tab" aria-controls="discover-tab-pane" aria-selected="false">Discover</button>
            <button class="tab-btn nav-item nav-link link-body-emphasis" id="sources-tab" data-tab-name="sources" data-bs-toggle="tab" data-bs-target="#sources-tab-pane" type="button" role="tab" aria-controls="sources-tab-pane" aria-selected="false">Sources</button>
        </nav>
    </div>
</div>
<hr class="m-0">