accounts/urls.py
from django.urls import path

from . import views


app_name = "accounts"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("login", views.LoginView.as_view(), name="login"),
    path("register", views.RegisterView.as_view(), name="register"),
    path("logout", views.LogoutView.as_view(), name="logout"),
    path("forgot-pass", views.ForgotPasswordView.as_view(), name="forgot-pass"),
    path("resend-verification", views.ResendVerificationView.as_view(), name="resend-verification"),
    path("verify/<str:token>", views.AccountVerificationView.as_view(), name="verify"),
    path("reset-pass/<str:token>", views.ResetPasswordView.as_view(), name="reset-pass"),
    path("profile", views.ProfileView.as_view(), name="profile"),
    path("change-profile-pic", views.ChangeProfilePicView.as_view(), name="change-profile-pic"),
    path("unsubscribe/", views.UnsubscribeView.as_view(), name="unsubscribe")
]

capstone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path

from . import views


app_name = "news"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("headlines/<str:category>", views.HeadlinesView.as_view(), name="headlines"),
    path("sources/", views.SourcesView.as_view(), name="sources"),
    path("search", views.SearchView.as_view(), name="search"),
    path("subscribe/", views.SubscribeView.as_view(), name="subscribe"),
    path("discover/", views.DiscoverView.as_view(), name="discover"),
    path("faqs/", views.FAQsView.as_view(), name="faqs"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("privacy-policy/", views.PrivacyPolicyView.as_view(), name="privacy-policy")
]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, SetPasswordForm, PasswordChangeForm, UserChangeForm
from django.contrib.auth import authenticate
from crispy_bootstrap5.bootstrap5 import FloatingField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit

from .models import User


# Create forms
"""
Registeration Form
"""
class RegisterationForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]
        
    # Creating Floating Fields using crispy bootstrap 5
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            FloatingField("username"),
            FloatingField("email"),
            FloatingField("password1"),
            FloatingField("password2"),
            Submit(name="submit", value="Sign up", css_class="btn-dark w-100")
        )
        
        for fieldname in ["username", "email", "password1", "password2"]:
            self.fields[fieldname].help_text = None
        
        
"""
Authentication Form
"""
class LoginForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
        
    class Meta:
        model = User
        fields = ["username", "password"]
    
    # Try to authenticate user and raise error if cannot
    def clean(self): 
        
        if not self.cleaned_data.get("username") or not self.cleaned_data["password"]:
            return
               
        username = self.cleaned_data["username"]
        password = self.cleaned_data["password"]
        
        if not authenticate(username=username, password=password):
            raise forms.ValidationError("Invalid username or password.")
        
    # Creating Floating Fields using crispy bootstrap 5
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            FloatingField("username"),
            FloatingField("password"),
            Submit(name="submit", value="Sign in", css_class="btn-dark w-100")
        )
        
        for fieldname in ["username", "password"]:
            self.fields[fieldname].help_text = None
        
        
"""
Find account form
"""
class FindAccountForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ["email"]
        
    # Try to find this account
    def clean(self):
        
        if not self.cleaned_data.get("email"):
            return
            
        email = self.cleaned_data["email"]
        try:
            user = User.objects.get(email=email)
            if user.is_active == False:
                raise forms.ValidationError("Account not verified.")
        except User.DoesNotExist:
            raise forms.ValidationError("Account does not exist.")
        
    # Creating Floating Fields using crispy bootstrap 5
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            FloatingField("email"),
            Submit(name="submit", value="Find Account", css_class="btn-dark w-100")
        )
        
        for fieldname in ["email"]:
            self.fields[fieldname].help_text = None
            
    
"""
Reset password form
"""
class ResetPasswordForm(SetPasswordForm):
        
    # Creating Floating Fields using crispy bootstrap 5
    def __init__(self, user, *args, **kwargs):
        
        # Set user
        self.user = user
        
        super(SetPasswordForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            FloatingField("new_password1"),
            FloatingField("new_password2"),
            Submit(name="submit", value="Reset Password", css_class="btn-dark w-100")
        )
        
        # Set labels
        for fieldname in ["new_password1", "new_password2"]:
            self.fields[fieldname].help_text = None
            

"""
Change password form
"""
class ChangePasswordForm(PasswordChangeForm):
    
    # Creating Floating Fields using crispy bootstrap 5
    def __init__(self, user, *args, **kwargs):
        
        # Set user
        self.user = user
        
        super(PasswordChangeForm, self).__init__(user, *args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            FloatingField("old_password"),
            FloatingField("new_password1"),
            FloatingField("new_password2"),
            Submit(name="submit", value="Change Password", css_class="btn-dark")
        )
        

"""
Resend verification form
"""
class VerificationForm(forms.Form):
    email = forms.EmailField()
    
    def clean(self):
        
        if not self.cleaned_data.get("email"):
            return
        
        email = self.cleaned_data["email"]
        
        # Check if user exists
        try:
            user = User.objects.get(email=email)
            if user.is_active == True:
                raise forms.ValidationError("Account already verified.")
        except User.DoesNotExist:
            raise forms.ValidationError("Account does not exist.")
        
    # Creating Floating Fields using crispy bootstrap 5
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            FloatingField("email"),
            Submit(name="submit", value="Send Email", css_class="btn-dark w-100")
        )
        
        for fieldname in ["email"]:
            self.fields[fieldname].help_text = None

accounts/views.py
import os
import json

from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages
from django.views import View
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin

from news.models import Subscription
from .models import User
from .forms import RegisterationForm, LoginForm, FindAccountForm, ResetPasswordForm, ChangePasswordForm, VerificationForm
from .utils import generate_email_token, send_email, parse_email_token


# Create your views here.
class IndexView(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse("accounts:profile"))
    
        return render(request, "accounts/index.html", {
            "login_form": LoginForm(),
            "register_form": RegisterationForm(),
            "forgot_form": FindAccountForm(),
            "verification_form": VerificationForm(),
            "view": "login"
        })
    
    
# Create your views here.
class LoginView(View):
    # POST
    def post(self, request, *args, **kwargs):
        # Create form obj with POST data
        form = LoginForm(request.POST)
        
        # Check if form valid
        if form.is_valid():
            # Get cleaned data
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            
            # Authenticate and login user
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return HttpResponseRedirect(reverse("news:index"))

        # Invalid form
        return render(request, "accounts/index.html", {
            "login_form": form,
            "register_form": RegisterationForm(),
            "forgot_form": FindAccountForm(),
            "verification_form": VerificationForm(),
            "view": "login"
        })


class LogoutView(View):
    # POST
    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(reverse("accounts:index"))


class RegisterView(View):
    # POST
    def post(self, request, *args, **kwargs):
        # Create form obj with POST data
        form = RegisterationForm(request.POST)
        
        # Check if valid form
        if form.is_valid():
            instance = form.save(commit=False)
            instance.is_active = False
            instance.save()
            
            email = form.cleaned_data["email"]
            token = generate_email_token(email)
            send_email(
                token=token,
                subject="News account verification",
                message="Please use the link to active your account",
                recipient_list=[email],
                email_for="verification",
            )
            messages.add_message(request, messages.SUCCESS, "Account activation email sent.")
            return HttpResponseRedirect(reverse("accounts:index"))
            
        return render(request, "accounts/index.html", {
            "register_form": form,
            "login_form": LoginForm(),
            "forgot_form": FindAccountForm(),
            "verification_form": VerificationForm(),
            "view": "register",
        })


class AccountVerificationView(View):
    # GET
    def get(self, request, token):
        # Parse token
        try:
            email = parse_email_token(token, 7200)
            user = User.objects.get(email=email)
            
            # Already activated
            if user.is_active == True:
                messages.add_message(request, messages.ERROR, "Already activated.")
                return HttpResponseRedirect(reverse("accounts:index"))
            
            user.is_active = True
            user.save()
            messages.add_message(request, messages.SUCCESS, "Account activated.")
            return HttpResponseRedirect(reverse("accounts:index"))
        except Exception as e:
            
            messages.add_message(request, messages.ERROR, "Token expired or invalid.")
            return HttpResponseRedirect(reverse("accounts:index"))
        
        
class ForgotPasswordView(View):
    # POST
    def post(self, request, *args, **kwargs):
        form = FindAccountForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            token = generate_email_token(email)
            send_email(
                token=token,
                subject="News account password reset",
                message="Please use this link to reset your password",
                recipient_list=[email],
                email_for="resetpassword"
            )
            messages.add_message(request, messages.SUCCESS, "An email has been sent.")
            
        return render(request, "accounts/index.html", {
            "login_form": LoginForm(),
            "register_form": RegisterationForm(),
            "forgot_form": form,
            "verification_form": VerificationForm(),
            "view": "forgot-pass"
        })
        
        
class ResetPasswordView(View):
    # GET
    def get(self, request, token):
        # Try to parse token
        try:
            email = parse_email_token(token, 7200)
            user = User.objects.get(email=email)
            
            return render(request, "accounts/resetpass-form.html", {
                "form": ResetPasswordForm(user=user),
                "token": token
            })
        except Exception as e:
            messages.add_message(request, messages.ERROR, "Token expired or invalid.")
            return HttpResponseRedirect(reverse("accounts:index"))
    
    # POST
    def post(self, request, token):
        # Try to parse token and get user
        try:
            email = parse_email_token(token, 7200)
            user = User.objects.get(email=email)
        except Exception as e:
            messages.add_message(request, messages.ERROR, "Token expired or invalid.")
            return HttpResponseRedirect(reverse("accounts:index"))
        
        # Reset user's password using POST data
        form = ResetPasswordForm(user, request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "Password reset successful.")
            return HttpResponseRedirect(reverse("accounts:index"))
        
        return render(request, "accounts/resetpass-form.html", {
            "form": form,
            "token": token
        })
        

class ResendVerificationView(View):
    def post(self, request, *args, **kwargs):   
        form = VerificationForm(request.POST)
        if form.is_valid():
            # Resend verification email
            email = form.cleaned_data["email"]
            token = generate_email_token(email)
            send_email(
                token=token,
                subject="News account verification",
                message="Please use the link to active your account",
                recipient_list=[email],
                email_for="verification",
            )
            messages.add_message(request, messages.SUCCESS, "Account activation email sent.")
            return HttpResponseRedirect(reverse("accounts:index"))
        
        # Invalid form data
        return render(request, "accounts/index.html", {
            "login_form": LoginForm(),
            "register_form": RegisterationForm(),
            "forgot_form": FindAccountForm(),
            "verification_form": form,
            "view": "verification"
        })
            
        
class ProfileView(LoginRequiredMixin, View):
    login_url = "/accounts/"
    
    # GET
    def get(self, request, *args, **kwargs):
        
        # Get subscripitons
        subs = request.user.subscriptions.all()
        
        return render(request, "accounts/profile.html", {
            "subscriptions": subs,
            "form": ChangePasswordForm(user=request.user),
        })
        
    # POST
    def post(self, request, *args, **kwargs):
        form = ChangePasswordForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "Password changed.")
            return HttpResponseRedirect(reverse("accounts:profile"))
        
        
        return render(request, "accounts/profile.html", {
            "form": form,
            "show_form": True
        })
        
        
class ChangeProfilePicView(LoginRequiredMixin, View):
    login_url = "/accounts/"
    
    def post(self, request, *args, **kwargs):
        if not request.FILES.get("file"):
            return HttpResponseRedirect(reverse("accounts:profile"))
        
        # Get user and file
        user = User.objects.get(pk=request.user.id)
        file = request.FILES["file"]
        
        # Check if default profile pic is true
        if not user.is_default_profile_pic:
            if os.path.exists(user.profile_pic.path):
                os.remove(user.profile_pic.path)
        else:
            user.is_default_profile_pic = False

        user.profile_pic = file
        user.save()
        
        return HttpResponseRedirect(reverse("accounts:profile"))
    

class UnsubscribeView(LoginRequiredMixin, View):
    login_url = "/acconunts/"
    
    def post(self, request, *args, **kwargs):
        # Load json data
        data = json.loads(request.body)
        if not data.get("source_id"):
            return JsonResponse({"error": "Invalid data."}, status=400)
        
        try:
            sub = Subscription.objects.get(source_id=data["source_id"], user=request.user)
            sub.delete()
            return JsonResponse({"msg": "Subscription removed.", "count": request.user.subscriptions.count()}, status=201)
        except Subscription.DoesNotExist:

accounts/templates/accounts/email.html
<h2 style="text-align: center;">{{ subject }}</h2>
<p style="text-align: center; margin: 1rem 0;">{{ message }}</p>

{% if email_for == "verification" %}
    <form action="{{ site_url }}{% url 'accounts:verify' token %}" target="_blank" method="get" style="text-align: center; margin: 1rem 0;">
        <button type="submit" style="padding: 10px; background-color: black; color: white; border: none;">Verify Account</button>
    </form>
{% elif email_for == "resetpassword" %}
    <form action="{{ site_url }}{% url 'accounts:reset-pass' token %}" target="_blank" method="get" style="text-align: center; margin: 1rem 0;">
        <button type="submit" style="padding: 10px; background-color: black; color: white; border: none;">Reset Password</button>
    </form>
{% endif %}

<small style="margin: 1rem 0;">Note: Token expires in 120 minutes</small>

accounts/templates/accounts/footer-lg.html
<div class="mt-auto bg-body-tertiary border-top">
    <div class="container">
        <footer class="footer pt-5">
            <div class="row justify-content-lg-between">
    
                <div class="col-3 mb-3">
                    <ul class="nav flex-column">
                        <li class="nav-item mb-2"><a href="{% url 'news:index' %}" class="nav-link p-0 text-body-secondary">Home</a></li>
                        <li class="nav-item mb-2"><a href="{% url 'news:search' %}" class="nav-link p-0 text-body-secondary">Search</a></li>
                        <li class="nav-item mb-2"><a href="{% url 'accounts:index' %}" class="nav-link p-0 text-body-secondary">Account</a></li>
                    </ul>
                </div>

                <div class="col-4 mb-3">
                    <ul class="nav flex-column">
                        <li class="nav-item mb-2"><a href="{% url 'news:faqs' %}" class="nav-link p-0 text-body-secondary">FAQs</a></li>
                        <li class="nav-item mb-2"><a href="{% url 'news:privacy-policy' %}" class="nav-link p-0 text-body-secondary">Privacy Policy</a></li>
                        <li class="nav-item mb-2"><a href="{% url 'news:about' %}" class="nav-link p-0 text-body-secondary">About Us</a></li>
                    </ul>
                </div>

                <div class="col-5 mb-3">
                    <ul class="list-unstyled d-flex justify-content-end align-items-center h-100">
                        <li class="ms-3"><a class="link-body-emphasis" href="https://www.facebook.com/profile.php?id=100082964377668&mibextid=ZbWKwL"><i class="fa fa-2x fa-facebook"></i></a></li>
                        <li class="ms-3"><a class="link-body-emphasis" href="https://youtube.com/@srkydev5727?si=DXxxpW-AAnEOUCOr"><i class="fa fa-2x fa-youtube-play"></i></a></li>
                        <li class="ms-3"><a class="link-body-emphasis" href="https://www.linkedin.com/in/shahrukh-khan-2b8968242/"><i class="fa fa-2x fa-linkedin"></i></a></li>
                        <li class="ms-3"><a class="link-body-emphasis" href="https://github.com/srky420/"><i class="fa fa-2x fa-github"></i></a></li>
                    </ul>
                </div>
            </div>

            <div class="py-4 border-top">
                <p>News © 2023 Company, Inc. All rights reserved.</p>
            </div>
        </footer>
    </div>
</div>

accounts/templates/accounts/footer-sm.html
<div class="m-0 mt-auto border-top"></div>
<div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-3">
      <p class="col-md-4 mb-0 text-body-secondary">News © 2023 Company, Inc</p>
  
      <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
      </a>
  
      <ul class="nav col-md-4 justify-content-end">
        <li class="nav-item"><a href="{% url 'news:index' %}" class="nav-link px-2 text-body-secondary">Home</a></li>
        <li class="nav-item"><a href="{% url 'news:search' %}" class="nav-link px-2 text-body-secondary">Search</a></li>
        <li class="nav-item"><a href="{% url 'news:faqs' %}" class="nav-link px-2 text-body-secondary">FAQs</a></li>
        <li class="nav-item"><a href="{% url 'news:about' %}" class="nav-link px-2 text-body-secondary">About</a></li>
      </ul>
    </footer>
</div>

accounts/templates/accounts/forgotpass-form.html
{% load crispy_forms_tags %}

<div class="form-signin w-100 mx-auto border shadow auth-form fade visually-hidden" id="forgot-pass">
    <form action="{% url 'accounts:forgot-pass' %}" method="post">
        <h3 class="mb-3 text-center">Find your account</h3>

        <!-- Messages -->
        {% if view == "forgot-pass" %}{% include "accounts/messages.html" %}{% endif %}

        {% csrf_token %}
        {% crispy forgot_form %}
        <p class="text-center my-2"><a class="link-underline" href="#" onclick="switch_view('login')">Go back</a></p>
    </form>
</div>

accounts/templates/accounts/index.html
{% extends "accounts/layout.html" %}

{% block body %}

    <div class="d-flex align-items-center justify-content-center main-div">
        <div class="banner-text mb-5 p-3">
            <h1>Stay informed by subscribing to hundreds of news sources.</h1>
        </div>

        <!-- Login view -->
        {% include "accounts/login-form.html" %}

        <!-- Register view -->
        {% include "accounts/register-form.html" %}

        <!-- Forgot pass view -->
        {% include "accounts/forgotpass-form.html" %}

        <!-- Resent verification view -->
        {% include "accounts/verification-form.html" %}
    </div>

    {{ view | json_script:"view" }}

{% endblock %}

accounts/templates/accounts/login-form.html
{% load crispy_forms_tags %}

<div class="form-signin w-100 mx-auto border shadow auth-form fade visually-hidden" id="login">
    <form action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        <h3 class="mb-3 text-center">Please sign in</h3>

        <!-- Messages -->
        {% if view == "login" %}{% include "accounts/messages.html" %}{% endif %}

        {% crispy login_form %}
        <p class="text-end my-2"><a class="link-underline" href="#" onclick="switch_view('forgot-pass')">Forgot Password?</a></p>
        <p class="text-center my-2">Don't have an account? <a class="link-underline" href="#" onclick="switch_view('register')">Sign up</a></p>
        <hr>
        <p class="text-center my-2">Didn't receive verification email? <a class="link-underline" href="#" onclick="switch_view('verification')">Resend</a></p>
    </form>
</div>

accounts/templates/accounts/messages.html
{% if messages %}
    {% for msg in messages %}
        <div class="alert alert-block alert-{% if msg.tags == 'error' %}danger{% else %}{{ msg.tags }}{% endif %}">
            <ul class="m-0"> 
                <li>
                    {{ msg }}
                </li> 
            </ul>
        </div>
    {% endfor %}
{% endif %}

accounts/templates/accounts/profile-pic.html
<div class="card text-bg-dark rounded-circle border-0 position-relative profile-pic-lg">
    <img src="{{ request.user.profile_pic.url }}" alt="" srcset="" class="card-img profile-pic profile-pic-lg">
    <div class="card-img-overlay profile-pic-upload" 
        onmouseout="this.querySelector('#file').classList.remove('show')" 
        onmouseover="this.querySelector('#file').classList.add('show');">
        <form action="{% url 'accounts:change-profile-pic' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="file" id="file" class="position-absolute w-100 fade z-3" onchange="this.form.submit()">
        </form>
        <div class="bg-dark bg-opacity-25 w-100 h-100 position-absolute rounded-circle start-0 top-0 profile-pic-overlay"></div>
    </div>
</div>

accounts/templates/accounts/profile.html
{% extends "accounts/layout.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block body %}

    <!-- Profile info -->
    <div class="mt-3 mb-5 text-center">
        <div class="d-flex justify-content-center w-100 ms-auto">
            {% include "accounts/profile-pic.html" %}
        </div>
        <div class="my-3">
            <h5>{{ request.user.username }}</h5>
            <p>{{ request.user.email }}</p>
            <p><small class="text-body-secondary">Date Joined: {{ request.user.date_joined }}</small></p>
        </div>
    </div>

    <!-- Profile accordion -->
    <div class="accordion my-5 rounded-0" id="accordionFlushExample">
        <div class="accordion-item border-2 rounded-0">
            <h2 class="accordion-header">
                <button class="accordion-button rounded-0 {% if not show_form %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                    <h3 class="m-0">Change Password</h3>
                </button>
            </h2>
            <div id="flush-collapseTwo" class="accordion-collapse collapse {% if show_form %}show{% endif %}" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">
                    {% include "accounts/messages.html" %}
                    {% crispy form %}
                </div>
            </div>
        </div>
        <div class="accordion-item border-2 rounded-0">
            <h2 class="accordion-header">
                <button class="accordion-button rounded-0 collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                    <h3 class="m-0">Subscriptions</h3>
                </button>
            </h2>
            <div id="flush-collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body p-0">

                    <div class="row mb-5 mx-0 overflow-auto" id="sources-div" style="max-height: 400px">
                    {% for source in subscriptions %}

                        <div class="col-lg-4 col-md-6 col-sm-12 py-3" id="{{ source.source_id }}">
                            <div class="px-3 d-flex flex-column h-100 position-relative">
                                <strong class="d-inline-block mb-2 text-primary-emphasis category-name">{{ source.source_category }}</strong>
                                <a href="#" class="mb-0 link-underline link-underline-opacity-0" onclick=""><h4>{{ source.source_name }}</h4></a>
                                <p class="my-2 text-wrap overflow-hidden">{{ source.source_description }}</p>
                                <button onclick="source_unsubscribe(this)" data-source-id="{{ source.source_id }}"
                                    class="btn btn-sm btn-secondary position-absolute top-0 end-0 m-2">
                                    <i class="fa fa-check"></i>
                                </button>
                            </div>
                        </div>

                    {% empty %}
                        <h2 class="h-100 text-center my-5">No subscriptions yet.</h2>
                    {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="w-100 text-end mb-5">
        <a class="btn btn-dark" href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out"></i> Logout</a>
    </div>

{% endblock %}

{% block scripts %}
    <script src="{% static 'accounts/unsubscribe.js' %}"></script>
{% endblock %}

accounts/templates/accounts/register-form.html
{% load crispy_forms_tags %}

<div class="form-signin w-100 mx-auto border shadow auth-form fade visually-hidden" id="register">
    <form action="{% url 'accounts:register' %}" method="post">
        {% csrf_token %}
        <h3 class="mb-3 text-center">Please sign up</h3>

        <!-- Messages -->
        {% if view == "register" %}{% include "accounts/messages.html" %}{% endif %}

        {% crispy register_form %}
        <p class="text-center my-2">Already have an account? <a class="link-underline" href="#" onclick="switch_view('login')">Sign in</a></p>
    </form>
</div>

accounts/templates/accounts/resetpass-form.html
{% extends "accounts/layout.html" %}

{% load crispy_forms_tags %}

{% block body %}

    <div class="form-signin w-100 mx-auto border shadow fade show">
        <form action="{% url 'accounts:reset-pass' token %}" method="post">
            {% csrf_token %}
            <h3 class="mb-3 text-center">Password Reset</h3>

            <!-- Messages -->
            {% include "accounts/messages.html" %}

            {% crispy form %}
        </form>
    </div>

{% endblock %}

accounts/templates/accounts/verification-form.html
{% load crispy_forms_tags %}

<div class="form-signin w-100 mx-auto border shadow auth-form fade visually-hidden" id="verification">
    <form action="{% url 'accounts:resend-verification' %}" method="post">
        {% csrf_token %}
        <h3 class="mb-3 text-center">Account Verification</h3>

        <!-- Messages -->
        {% if view == "verification" %}{% include "accounts/messages.html" %}{% endif %}

        {% crispy verification_form %}
        <p class="text-center my-2"><a class="link-underline" href="#" onclick="switch_view('login')">Go back</a></p>
    </form>
</div>